spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境111
  application: 
    name: microservicecloud-config-atguigu-dev
---
spring:
  profiles: test   #测试环境111
  application: 
    name: microservicecloud-config-atguigu-test
#  请保存为UTF-8格式
